import streamlit as st

def format_for_platform(raw_text, link, platform):
    """Formats the raw bot response based on the target platform's limitations."""
    
    if platform == "Web":
        # Web can handle rich Markdown and clean hyperlinks
        formatted_text = f"### 🎓 **Update**\n{raw_text}\n\n[Click here for more details]({link})"
        
    elif platform == "Mobile App":
        # Mobile needs to be concise with simple spacing
        formatted_text = f"🔔 {raw_text}\n\nTap the link below:\n{link}"
        
    elif platform == "WhatsApp":
        # WhatsApp uses * for bold, _ for italics, and raw URLs
        # Let's replace standard markdown ** with WhatsApp's *
        whatsapp_text = raw_text.replace("**", "*")
        formatted_text = f"🤖 *Institute Alert*\n_{whatsapp_text}_\n\nLink: {link}"
        
    return formatted_text

def run_week9():
    st.header("📅 Week 9: Cross-Platform Prototyping")
    st.write("This module simulates how the exact same backend response is formatted differently depending on the platform receiving it.")

    # A mock raw response generated by your bot's backend
    raw_bot_response = "The **Semester 5 CS** exams have been rescheduled to next Monday."
    reference_link = "https://institute.edu/exams/sem5"

    st.write("### ⚙️ Backend Logic Output:")
    st.code(f"Raw Text: {raw_bot_response}\nLink: {reference_link}", language="text")

    st.divider()

    # Simulator UI
    st.write("### 📱 Platform Simulator")
    selected_platform = st.radio("Select the platform to send this message to:", ["Web", "Mobile App", "WhatsApp"], horizontal=True)

    if st.button("Generate Formatted Response"):
        # Run the formatter function
        final_output = format_for_platform(raw_bot_response, reference_link, selected_platform)
        
        st.success(f"**Sending to {selected_platform}:**")
        
        # Displaying it in a code block so you can see the raw formatting characters
        st.code(final_output, language="markdown")
        
        # For Web and Mobile, we can show how it actually renders in Streamlit
        if selected_platform != "WhatsApp":
            st.write("**How it renders to the user:**")
            st.markdown(final_output)

if __name__ == "__main__":
    run_week9()